### 데이터 타입 지정 ndarray
- numpy는 하나의 데이터 type만 배열에 넣을 수 있다.<br>
 -> List와 가장 큰 차이점, Dynamic typing not supported(리스트에는 여러 데이터타입 넣는게 가능)<br>

In [34]:
import numpy as np
test_array = np.array([1,4,5,"8"], float) # float으로 타입 지정 -> 자동으로 float64
print(test_array)
print(f"{test_array.dtype = }")

[1. 4. 5. 8.]
test_array.dtype = dtype('float64')


### 얕은 복사와 깊은 복사

In [10]:
a=[[1,2],[3,4]]
b=a.copy() # 얕은 복사의 한계
a[0][0]=100
print(a)
print(b)

[[100, 2], [3, 4]]
[[100, 2], [3, 4]]


In [11]:
import copy
a=[[1,2],[3,4]]
b = copy.deepcopy(a)
a[0][0]=100
print(a)
print(b)

[[100, 2], [3, 4]]
[[1, 2], [3, 4]]


### flatten
: 다차원 array를 1차원 array로 변환

In [46]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4,], [1,2,5,8]]]
test_arr = np.array(test_matrix)
print(f"{test_arr.shape = }\n{test_arr = }")
test_arr.flatten()

test_arr.shape = (2, 2, 4)
test_arr = array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])


array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

### indexing

In [48]:
test = test_arr.reshape(4,4)
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [181]:
print(f"{test[0,1] = }")
print(f"{test[0][1] = }")
#똑같다.

test[0,1] = 2
test[0][1] = 2


### slicing

In [55]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [53]:
test[:,2:] # 전체 Row, 2열 이상

array([[3, 4],
       [5, 8],
       [3, 4],
       [5, 8]])

In [54]:
test[1,1:3] # 1행, 1~2열

array([2, 5])

In [56]:
test[1:3] # 1~2행

array([[1, 2, 5, 8],
       [1, 2, 3, 4]])

### np.arange

In [58]:
np.arange(0, 10, 2) # (시작, 끝, step)

array([0, 2, 4, 6, 8])

In [59]:
np.arange(30) # 0~29까지

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
np.arange(30).reshape(5,6) # 5행 6열

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### np.ones, zeros

In [63]:
ones = np.ones((2,5), dtype=int)
print(f"{ones.dtype = }")
ones
# zeros도 마찬가지

ones.dtype = dtype('int64')


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### np.ones_like, np.zeros_like

In [64]:
print(f"{test.shape = }")
np.ones_like(test)

test.shape = (4, 4)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### np.identity
: 단위 행렬을 생성

In [69]:
i = np.identity(n=3, dtype=int)
print(f"{i.dtype = }")
i

i.dtype = dtype('int64')


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### np.eye
: 대각선이 1인 행렬, k(start index) 변경가능

In [70]:
e = np.eye(N=3, M=5, dtype=int)
print(f"{e.dtype = }")
e

e.dtype = dtype('int64')


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.eye(3,5,k=2) # start index 2 (2열부터 대각행렬)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random sampling

In [74]:
np.random.uniform(0,1,10).reshape(2,5) # 0~1 균등분포

array([[0.61458193, 0.11553319, 0.3738878 , 0.11206745, 0.99118032],
       [0.84089873, 0.90170199, 0.32228599, 0.10527329, 0.24510245]])

In [77]:
np.random.normal(0,1,8).reshape(2,4) # 정규분포 - 중앙값:0, 표준편차:1, 8개 값

array([[ 1.77916019,  0.60619016,  0.06288257,  1.57586799],
       [-1.36382115,  0.0531033 ,  1.91525422,  0.70426533]])

### axis

1차원 -> 2차원 -> 3차원으로 갈때<br>
shape는 열 -> 행, 열 -> 면, 행, 열 처럼 새로나오는 차원이 왼쪽에 붙는다.<br>
**이 떄 axis는 새롭게 생긴 차원(shape 에서 제일 왼쪾에 있는 차원)이 항상 0이다**

In [85]:
# 1차원 30개 짜리가 있을 때
on = np.ones(30)
print(f"{on.shape = }\n{on = }")
# 열이 axis=0

on.shape = (30,)
on = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [86]:
on = on.reshape(5,6)
print(f"{on.shape = }\n{on = }")
# 2차원이 되면 3행, 9열
# 행이 axis=0

on.shape = (5, 6)
on = array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])


In [93]:
on = on.reshape(2,3,5)
print(f"{on.shape = }\n{on = }")
# 3차원이면 2면, 3행, 5열
# 면이 axis=0

on.shape = (2, 3, 5)
on = array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


In [94]:
on.sum(axis=0) # 면을 기준하여 수직으로 합

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [95]:
on.sum(axis=1) # 행을 기준하여 수직으로 합

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [96]:
on.sum(axis=2) # 열을 기준하여 수직으로 합

array([[5., 5., 5.],
       [5., 5., 5.]])

### concatenate: np.vstack, np.hstack
: Numpy array를 합치는 함수<br>
<br><img src=https://blog.kakaocdn.net/dn/rSWwB/btrGRjD076R/b2hLJt25wlC2y21oDSmal0/img.png width=1000>

In [106]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b)) # vertical 수직 방향으로 붙인다

array([[1, 2, 3],
       [2, 3, 4]])

In [117]:
a.reshape(1,-1)

array([[1, 2, 3]])

In [120]:
# concatenate로 axis 지정하면 vstack 구현 가능
np.concatenate( (a.reshape(1,3),b.reshape(1,3)), axis=0 )

array([[1, 2, 3],
       [2, 3, 4]])

In [121]:
a = np.array([1,2,3]).reshape(3,-1)
b = np.array([2,3,4]).reshape(3,-1)
np.hstack((a,b)) # horizontal 수평 방향으로 붙인다

array([[1, 2],
       [2, 3],
       [3, 4]])

In [126]:
# 마찬가지로 concatenate로 hstack도 구현가능
np.concatenate((a,b), axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

### array 연산
: Numpy는 기본적으로 array간의 기본적인 사칙 연산 지원

In [128]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [129]:
test + test

array([[ 2,  4,  6,  8],
       [ 2,  4, 10, 16],
       [ 2,  4,  6,  8],
       [ 2,  4, 10, 16]])

In [130]:
test - test

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [131]:
test * test

array([[ 1,  4,  9, 16],
       [ 1,  4, 25, 64],
       [ 1,  4,  9, 16],
       [ 1,  4, 25, 64]])

In [132]:
test / test

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### broadcasting
Shape이 다른 배열 간 연산할 때 퍼뜨려주는기능<br>
-> 스칼라값과 배열간 연산할 때 유용하다.

In [133]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [138]:
test + 3 # 스칼라 값을 test의 모든 위치에 더해준다

array([[ 4,  5,  6,  7],
       [ 4,  5,  8, 11],
       [ 4,  5,  6,  7],
       [ 4,  5,  8, 11]])

#### broadcasting 유의할부분
: 서로 다른 차원의 행렬에 대해 연산할 때, 차원을 맞춰서 계산해준다. (규칙이 있다)<br>
<br><img src=https://blog.kakaocdn.net/dn/k8ytY/btrGO7ZFLgr/y7aVMp8je7PznfEzZCm52K/img.png width=1000>

### Comparison

In [139]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [141]:
test > 3 # 개별 인자들에 대해 비교 연산결과 반환

array([[False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True]])

### np.where

In [154]:
a = np.arange(10)

In [155]:
np.where(a > 3, 100, 0) # where(condition, TRUE, FALSE)

array([  0,   0,   0,   0, 100, 100, 100, 100, 100, 100])

In [156]:
np.where(a > 3) # Index값 반환 -> 정렬과 많이 쓴다.

(array([4, 5, 6, 7, 8, 9]),)

### argmax(), argmin()
: 최대, 최소값의 인덱스 반환

In [157]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
np.argmax(a), np.argmin(a)

(9, 0)

### boolean index
조건이 True인 index의 element만 추출

In [159]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [162]:
test[test>3]

array([4, 5, 8, 4, 5, 8])

In [167]:
B = test > 3
B

array([[False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True]])

In [168]:
B.astype(int) # binary로 바꿀 수 있음

array([[0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 1]])

### fancy index
: numpy array를 index value로 사용해서 값을 추출하는 방법

In [171]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1],int)
a[b] # b를 인덱스 값으로 a에서 값 추출

array([2, 2, 4, 8, 6, 4])

In [172]:
a.take(b) # 위처럼 쓰면 가독성이 떨어지니 이렇게 씀
# take 함수: bracket index와 같은 효과

array([2, 2, 4, 8, 6, 4])

In [173]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [176]:
# fancy index는 Matrix 형태의 데이터도 가능
test[b,b] 

array([1, 1, 2, 8, 3, 2])

### numpy object - npy
: Numpy object를 pickle 형태로 데이터 저장하고 불러오는게 가능<br>
**확장자는 .npy이고, 피클처럼 Binary로 저장**

In [177]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [178]:
np.save("npy_test", arr=test)

In [180]:
np.load("npy_test.npy")

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])