### 데이터 타입 지정 ndarray
- numpy는 하나의 데이터 type만 배열에 넣을 수 있다.<br>
 -> List와 가장 큰 차이점, Dynamic typing not supported(리스트에는 여러 데이터타입 넣는게 가능)<br>

In [34]:
import numpy as np
test_array = np.array([1,4,5,"8"], float) # float으로 타입 지정 -> 자동으로 float64
print(test_array)
print(f"{test_array.dtype = }")

[1. 4. 5. 8.]
test_array.dtype = dtype('float64')


### 얕은 복사와 깊은 복사

In [10]:
a=[[1,2],[3,4]]
b=a.copy() # 얕은 복사의 한계
a[0][0]=100
print(a)
print(b)

[[100, 2], [3, 4]]
[[100, 2], [3, 4]]


In [11]:
import copy
a=[[1,2],[3,4]]
b = copy.deepcopy(a)
a[0][0]=100
print(a)
print(b)

[[100, 2], [3, 4]]
[[1, 2], [3, 4]]


### flatten
: 다차원 array를 1차원 array로 변환

In [46]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4,], [1,2,5,8]]]
test_arr = np.array(test_matrix)
print(f"{test_arr.shape = }\n{test_arr = }")
test_arr.flatten()

test_arr.shape = (2, 2, 4)
test_arr = array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])


array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

### indexing

In [48]:
test = test_arr.reshape(4,4)
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [52]:
print(f"{test[0,1] = }")
print(f"{test[0][0] = }")
#똑같다.

test[0,1] = 2
test[0][0] = 1


### slicing

In [55]:
test

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [53]:
test[:,2:] # 전체 Row, 2열 이상

array([[3, 4],
       [5, 8],
       [3, 4],
       [5, 8]])

In [54]:
test[1,1:3] # 1행, 1~2열

array([2, 5])

In [56]:
test[1:3] # 1~2행

array([[1, 2, 5, 8],
       [1, 2, 3, 4]])

### np.arange

In [58]:
np.arange(0, 10, 2) # (시작, 끝, step)

array([0, 2, 4, 6, 8])

In [59]:
np.arange(30) # 0~29까지

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])